[base]
Title="HCTF"
BeginTime="2020-01-14T08:00:00+08:00"
RestTime=[
    ["2020-01-14T18:00:00+08:00","2020-01-15T8:00:00+08:00"],
]
EndTime="2020-01-16T22:00:00+08:00"
Duration=2    # 分钟

Salt="E99E99E99"

Port=":19999"

FlagPrefix="hctf{"
FlagSuffix="}"

CheckDownScore=50
AttackScore=50

[mysql]
DBHost="localhost:3306"
DBUsername="root"
DBPassword="root"
DBName="cardinal"