name: Go
on:
  push:
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=30m

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: cardinal_passw0rd
        ports:
          - 3306:3306
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache downloaded modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: go test -v -race ./...
        env:
          DBPORT: 3306
          DBHOST: localhost
          DBUSER: root
          PGPASSWORD: cardinal_passw0rd